name: squaremap-Towny
version: ${project.version}
main: me.ar00n.squaremaptowny.squaremapTowny
api-version: 1.18
depend: [ squaremap, Towny ]
authors: [ Silverwolfg11, ar00n ]
description: A fork of a Pl3x Map addon to support Towny on squaremap

commands:
  squaremaptowny:
    description: Command for sqaremap-Towny
    aliases: [sqmaptowny, maptowny]
    permission: squaremapTowny.use

permissions:
  squaremapTowny.admin:
    description: Admin permission for squaremap-Towny
    default: false
    children:
      squaremapTowny.use: true
      squaremapTowny.reload: true
      squaremapTowny.render: true
      squaremapTowny.unrender: true

  squaremapTowny.use:
    description: Permission to use the squaremap-Towny command
    default: op

  squaremapTowny.reload:
    description: Allows access to sub-cmd to reload squaremap-Towny
    default: op

  squaremapTowny.render:
    description: Allows access to sub-cmd to render a town on the Squaremap
    default: op

  squaremapTowny.unrender:
    description: Allows access to sub-cmd to unrender a town on the Squaremap
    default: op
